# Region Observation (P6) — geometric layout regions
from .region_config import (
    RegionConfig, DEFAULT_CONFIG, to_dict,
    REGION_TYPE_PAGE_TOP, REGION_TYPE_PAGE_BOTTOM, REGION_TYPE_FULL_WIDTH,
    REGION_TYPE_COLUMN, REGION_TYPE_DENSE, REGION_TYPE_SPARSE, REGION_TYPE_UNKNOWN,
    ALL_REGION_TYPES,
    METHOD_TOP_BAND, METHOD_BOTTOM_BAND, METHOD_FULL_WIDTH, METHOD_COLUMN_GROUP,
    METHOD_DENSITY_CLUSTER_DENSE, METHOD_DENSITY_CLUSTER_SPARSE, METHOD_UNASSIGNABLE,
    CONFIDENCE_HIGH, CONFIDENCE_MEDIUM, CONFIDENCE_LOW, CONFIDENCE_UNKNOWN,
    COORD_ORIGIN_PDF_TOP_LEFT,
    RULE_TOP_BAND, RULE_BOTTOM_BAND, RULE_FULL_WIDTH, RULE_COLUMN_GROUP,
    RULE_DENSE_CLUSTER, RULE_SPARSE_CLUSTER, RULE_UNASSIGNABLE,
)
from .region_observation import RegionObservation, PageRegionSet
from .region_engine import compute_page_regions, verify_region_coverage
