"""
ShadowCompositionCandidate — Simulated composition proposal.

Generated by CompositionSimulator (Phase 6.1-L2), this represents a
WHAT-IF scenario: "given these production evidence and capability
matches, a composition of X capabilities could be proposed."

NEVER triggers real execution. Always marked SHADOW_ONLY.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from uuid import uuid4


@dataclass
class CapabilityRef:
    """A reference to a Capability within a composition candidate."""
    capability_id: str = ""
    capability_name: str = ""
    role_in_composition: str = ""  # e.g. "primary", "dependency", "enhancer"


@dataclass
class StepProposal:
    """A proposed execution step within a composition plan."""
    step_id: int = 0
    capability_id: str = ""
    action: str = ""
    depends_on: List[int] = field(default_factory=list)


@dataclass
class ExecutionPlanProposal:
    """A simulated execution plan proposal (never executed)."""
    steps: List[StepProposal] = field(default_factory=list)
    estimated_complexity: str = "LOW"  # "LOW" | "MEDIUM" | "HIGH"


@dataclass
class SimulationMetadata:
    """Metadata about the simulation run."""
    simulation_duration_ms: float = 0.0
    planner_version: str = "DESIGN_ONLY"
    dependency_graph_version: str = "DESIGN_ONLY"


@dataclass
class ShadowCompositionCandidate:
    """Simulated composition candidate — a WHAT-IF scenario.

    Fields:
        candidate_id: Unique candidate identifier (UUID)
        observation_id: Associated ShadowObservation ID
        document_id: Source document identifier
        composition_type: Strategy type (sequential/parallel/hierarchical)
        included_capabilities: Capabilities in this composition
        composition_score: Quality score (0.0-1.0)
        execution_plan_proposal: Simulated execution plan (never executed)
        simulation_metadata: Simulation run metadata
        shadow_marked: Always True
    """

    # ── Identity ──
    candidate_id: str = field(default_factory=lambda: str(uuid4()))
    observation_id: str = ""
    document_id: str = ""

    # ── Composition ──
    composition_type: str = "sequential"  # "sequential" | "parallel" | "hierarchical"
    included_capabilities: List[CapabilityRef] = field(default_factory=list)
    composition_score: float = 0.0

    # ── Execution Plan (simulated) ──
    execution_plan_proposal: Optional[ExecutionPlanProposal] = None

    # ── Simulation Metadata ──
    simulation_metadata: SimulationMetadata = field(
        default_factory=SimulationMetadata
    )

    # ── Shadow Marker ──
    shadow_marked: bool = True
    shadow_version: str = "1.0"
    origin: str = "composition_shadow_storage"

    # ── Metadata ──
    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def capability_count(self) -> int:
        return len(self.included_capabilities)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "candidate_id": self.candidate_id,
            "observation_id": self.observation_id,
            "document_id": self.document_id,
            "composition_type": self.composition_type,
            "included_capabilities": [
                {
                    "capability_id": c.capability_id,
                    "capability_name": c.capability_name,
                    "role_in_composition": c.role_in_composition,
                }
                for c in self.included_capabilities
            ],
            "composition_score": self.composition_score,
            "execution_plan_proposal": (
                {
                    "steps": [
                        {
                            "step_id": s.step_id,
                            "capability_id": s.capability_id,
                            "action": s.action,
                            "depends_on": s.depends_on,
                        }
                        for s in self.execution_plan_proposal.steps
                    ],
                    "estimated_complexity": self.execution_plan_proposal.estimated_complexity,
                }
                if self.execution_plan_proposal
                else None
            ),
            "simulation_metadata": {
                "simulation_duration_ms": self.simulation_metadata.simulation_duration_ms,
                "planner_version": self.simulation_metadata.planner_version,
                "dependency_graph_version": self.simulation_metadata.dependency_graph_version,
            },
            "shadow_marked": self.shadow_marked,
            "shadow_version": self.shadow_version,
            "origin": self.origin,
            "timestamp": self.timestamp,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ShadowCompositionCandidate":
        cand = cls(
            candidate_id=data.get("candidate_id", ""),
            observation_id=data.get("observation_id", ""),
            document_id=data.get("document_id", ""),
            composition_type=data.get("composition_type", "sequential"),
            composition_score=data.get("composition_score", 0.0),
            shadow_marked=data.get("shadow_marked", True),
            shadow_version=data.get("shadow_version", "1.0"),
            origin=data.get("origin", "composition_shadow_storage"),
            timestamp=data.get("timestamp", ""),
            metadata=data.get("metadata", {}),
        )
        cand.included_capabilities = [
            CapabilityRef(
                capability_id=c.get("capability_id", ""),
                capability_name=c.get("capability_name", ""),
                role_in_composition=c.get("role_in_composition", ""),
            )
            for c in data.get("included_capabilities", [])
        ]
        ep = data.get("execution_plan_proposal")
        if ep:
            cand.execution_plan_proposal = ExecutionPlanProposal(
                steps=[
                    StepProposal(
                        step_id=s.get("step_id", 0),
                        capability_id=s.get("capability_id", ""),
                        action=s.get("action", ""),
                        depends_on=s.get("depends_on", []),
                    )
                    for s in ep.get("steps", [])
                ],
                estimated_complexity=ep.get("estimated_complexity", "LOW"),
            )
        sm = data.get("simulation_metadata", {})
        cand.simulation_metadata = SimulationMetadata(
            simulation_duration_ms=sm.get("simulation_duration_ms", 0.0),
            planner_version=sm.get("planner_version", "DESIGN_ONLY"),
            dependency_graph_version=sm.get("dependency_graph_version", "DESIGN_ONLY"),
        )
        return cand

    def __repr__(self) -> str:
        return (
            f"ShadowCompositionCandidate(id={self.candidate_id[:8]}..., "
            f"doc={self.document_id}, "
            f"type={self.composition_type}, "
            f"caps={self.capability_count}, "
            f"score={self.composition_score:.2f}, "
            f"shadow_marked={self.shadow_marked})"
        )