"""
ShadowTraceRecord — Complete Shadow pipeline trace.

Phase 6.1-L4: Generated by Shadow Tracer, this records the full
end-to-end lifecycle of a Shadow pipeline execution — from Observation
capture through Validation — without modifying production state.

NEVER triggers production execution. Always marked SHADOW_ONLY.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import uuid4


class TracePhase(Enum):
    """Phases in the Shadow pipeline lifecycle."""
    CAPTURE = "CAPTURE"       # Observation capture
    SIMULATE = "SIMULATE"     # Composition simulation
    VALIDATE = "VALIDATE"     # Validation checks
    TRACE = "TRACE"           # Trace assembly
    GOVERNANCE = "GOVERNANCE" # Governance verification


class TraceStatus(Enum):
    """Status of a single stage or the entire trace."""
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    SKIPPED = "SKIPPED"
    PENDING = "PENDING"


@dataclass
class StageRecord:
    """A single stage within the Shadow pipeline trace.

    Fields:
        stage_name: Phase name (CAPTURE/SIMULATE/VALIDATE/TRACE/GOVERNANCE)
        stage_id: Unique stage identifier
        start_time: Stage start timestamp
        end_time: Stage end timestamp
        status: Stage outcome (SUCCESS/FAILURE/SKIPPED)
        input_ref: Reference to the input entity ID
        output_ref: Reference to the output entity ID
        errors: Error messages (if any)
    """
    stage_name: str = "CAPTURE"  # CAPTURE | SIMULATE | VALIDATE | TRACE | GOVERNANCE
    stage_id: str = ""
    start_time: str = ""
    end_time: str = ""
    status: str = "PENDING"      # SUCCESS | FAILURE | SKIPPED | PENDING
    input_ref: str = ""
    output_ref: str = ""
    errors: List[str] = field(default_factory=list)

    @property
    def duration_ms(self) -> float:
        """Compute stage duration in milliseconds."""
        if not self.start_time or not self.end_time:
            return 0.0
        try:
            start = datetime.fromisoformat(self.start_time)
            end = datetime.fromisoformat(self.end_time)
            return (end - start).total_seconds() * 1000
        except (ValueError, TypeError):
            return 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "stage_name": self.stage_name,
            "stage_id": self.stage_id,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "status": self.status,
            "input_ref": self.input_ref,
            "output_ref": self.output_ref,
            "errors": self.errors,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "StageRecord":
        return cls(
            stage_name=data.get("stage_name", "CAPTURE"),
            stage_id=data.get("stage_id", ""),
            start_time=data.get("start_time", ""),
            end_time=data.get("end_time", ""),
            status=data.get("status", "PENDING"),
            input_ref=data.get("input_ref", ""),
            output_ref=data.get("output_ref", ""),
            errors=data.get("errors", []),
        )


@dataclass
class ShadowTraceRecord:
    """Complete Shadow pipeline trace record.

    Documents the full lifecycle of one Shadow pipeline execution:
    Observation → Simulation → Validation → Governance → Trace assembly.

    Fields:
        trace_id: Unique trace identifier (UUID)
        pipeline_id: Pipeline run identifier (groups multiple stages)
        document_id: Source document identifier
        start_timestamp: Pipeline start time
        end_timestamp: Pipeline end time
        pipeline_stages: Ordered list of stage records
        observation_ref: Associated ShadowObservation ID
        candidate_refs: Associated ShadowCompositionCandidate IDs
        validation_ref: Associated ShadowValidationResult ID
        production_trace_id: Cross-reference to production Trace (for audit)
        comparison_summary: Production vs Shadow comparison (optional)
        shadow_marked: Always True
    """

    # ── Identity ──
    trace_id: str = field(default_factory=lambda: str(uuid4()))
    pipeline_id: str = ""
    document_id: str = ""

    # ── Timing ──
    start_timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    end_timestamp: str = ""

    # ── Pipeline Stages ──
    pipeline_stages: List[StageRecord] = field(default_factory=list)

    # ── References ──
    observation_ref: str = ""
    candidate_refs: List[str] = field(default_factory=list)
    validation_ref: str = ""
    production_trace_id: Optional[str] = None

    # ── Comparison ──
    comparison_summary: Optional[Dict[str, Any]] = None

    # ── Shadow Marker ──
    shadow_marked: bool = True
    shadow_version: str = "1.0"
    origin: str = "composition_shadow_storage"

    # ── Metadata ──
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def total_duration_ms(self) -> float:
        """Compute total pipeline duration in milliseconds."""
        if not self.start_timestamp or not self.end_timestamp:
            return 0.0
        try:
            start = datetime.fromisoformat(self.start_timestamp)
            end = datetime.fromisoformat(self.end_timestamp)
            return (end - start).total_seconds() * 1000
        except (ValueError, TypeError):
            return 0.0

    @property
    def stage_count(self) -> int:
        """Number of stages in the pipeline."""
        return len(self.pipeline_stages)

    @property
    def successful_stages(self) -> int:
        """Count of SUCCESS stages."""
        return sum(1 for s in self.pipeline_stages if s.status == "SUCCESS")

    @property
    def failed_stages(self) -> int:
        """Count of FAILURE stages."""
        return sum(1 for s in self.pipeline_stages if s.status == "FAILURE")

    @property
    def skipped_stages(self) -> int:
        """Count of SKIPPED stages."""
        return sum(1 for s in self.pipeline_stages if s.status == "SKIPPED")

    @property
    def overall_status(self) -> str:
        """Overall pipeline status: SUCCESS if all stages succeeded, FAILURE otherwise."""
        if not self.pipeline_stages:
            return "PENDING"
        if any(s.status == "FAILURE" for s in self.pipeline_stages):
            return "FAILURE"
        if all(s.status == "SUCCESS" or s.status == "SKIPPED"
               for s in self.pipeline_stages):
            return "SUCCESS"
        if any(s.status == "PENDING" for s in self.pipeline_stages):
            return "PENDING"
        return "SUCCESS"

    def get_stage(self, stage_name: str) -> Optional[StageRecord]:
        """Find a stage by name."""
        for s in self.pipeline_stages:
            if s.stage_name == stage_name:
                return s
        return None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "trace_id": self.trace_id,
            "pipeline_id": self.pipeline_id,
            "document_id": self.document_id,
            "start_timestamp": self.start_timestamp,
            "end_timestamp": self.end_timestamp,
            "pipeline_stages": [s.to_dict() for s in self.pipeline_stages],
            "observation_ref": self.observation_ref,
            "candidate_refs": self.candidate_refs,
            "validation_ref": self.validation_ref,
            "production_trace_id": self.production_trace_id,
            "comparison_summary": self.comparison_summary,
            "shadow_marked": self.shadow_marked,
            "shadow_version": self.shadow_version,
            "origin": self.origin,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ShadowTraceRecord":
        trace = cls(
            trace_id=data.get("trace_id", ""),
            pipeline_id=data.get("pipeline_id", ""),
            document_id=data.get("document_id", ""),
            start_timestamp=data.get("start_timestamp", ""),
            end_timestamp=data.get("end_timestamp", ""),
            observation_ref=data.get("observation_ref", ""),
            candidate_refs=data.get("candidate_refs", []),
            validation_ref=data.get("validation_ref", ""),
            production_trace_id=data.get("production_trace_id"),
            comparison_summary=data.get("comparison_summary"),
            shadow_marked=data.get("shadow_marked", True),
            shadow_version=data.get("shadow_version", "1.0"),
            origin=data.get("origin", "composition_shadow_storage"),
            metadata=data.get("metadata", {}),
        )
        trace.pipeline_stages = [
            StageRecord.from_dict(s) for s in data.get("pipeline_stages", [])
        ]
        return trace

    def __repr__(self) -> str:
        return (
            f"ShadowTraceRecord(id={self.trace_id[:8]}..., "
            f"doc={self.document_id}, "
            f"stages={self.stage_count}, "
            f"status={self.overall_status}, "
            f"shadow_marked={self.shadow_marked})"
        )