"""
Phase 6.0: Composition Planner — Skeleton

Design Artifact 2: Generates composition proposals by evaluating which
Capabilities can be composed together safely.

STATUS: DESIGN_ONLY
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional

__all__ = [
    "CompositionStrategy",
    "CompositionRule",
    "CompositeCapabilityProposal",
    "PlannerOutput",
    "CompositionPlanner",
]

# ═══════════════════════════════════════════════════════════════════════════
# Enums
# ═══════════════════════════════════════════════════════════════════════════


class CompositionStrategy(Enum):
    """Strategy for composing capabilities."""

    SEQUENTIAL = "sequential"       # Execute in order: A → B → C
    PARALLEL = "parallel"           # Execute concurrently: A || B || C
    HIERARCHICAL = "hierarchical"   # Nested execution: A(B(C))
    CONDITIONAL = "conditional"     # Branch on condition: if X then A else B


# ═══════════════════════════════════════════════════════════════════════════
# Data Models
# ═══════════════════════════════════════════════════════════════════════════


@dataclass
class CompositionRule:
    """A rule used by the planner to evaluate composition candidates."""

    rule_type: str = ""              # e.g., "dependency", "conflict", "ordering"
    condition: str = ""              # Human-readable condition description
    action: str = ""                 # e.g., "allow", "block", "warn"
    priority: int = 0                # Higher = more important
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class CompositeCapabilityProposal:
    """A proposal for composing multiple capabilities together.

    Phase 6.0: Schema only. Generated by CompositionPlanner in Phase 6.1+.
    """

    proposal_id: str = ""
    capabilities: List[str] = field(default_factory=list)  # capability_ids
    strategy: CompositionStrategy = CompositionStrategy.SEQUENTIAL
    constraints: List[CompositionRule] = field(default_factory=list)
    score: float = 0.0               # Composition score (0-1)
    rationale: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class PlannerOutput:
    """Output from the CompositionPlanner.

    Phase 6.0: Schema only.
    """

    proposals: List[CompositeCapabilityProposal] = field(default_factory=list)
    rejected_candidates: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


# ═══════════════════════════════════════════════════════════════════════════
# CompositionPlanner — Interface Skeleton
# ═══════════════════════════════════════════════════════════════════════════


class CompositionPlanner:
    """Generates composition proposals for combining Capabilities.

    Phase 6.0: DESIGN_ONLY — all methods raise NotImplementedError.
    Phase 6.1+: Shadow implementation with DependencyGraph integration.
    """

    STATUS = "DESIGN_ONLY"

    def __init__(self, dependency_graph: Optional[Any] = None):
        """Initialize the planner with an optional dependency graph.

        Phase 6.0: DESIGN_ONLY.
        """
        self._graph = dependency_graph

    def generate_proposal(
        self,
        capability_ids: List[str],
        strategy: CompositionStrategy = CompositionStrategy.SEQUENTIAL,
        **kwargs,
    ) -> CompositeCapabilityProposal:
        """Generate a composition proposal for the given capabilities.

        Phase 6.0: NOT_IMPLEMENTED.
        """
        raise NotImplementedError(
            "Phase 6.0: DESIGN_ONLY. generate_proposal() will be implemented in Phase 6.1."
        )

    def evaluate_candidate(
        self, candidate: CompositeCapabilityProposal
    ) -> float:
        """Evaluate a composition candidate and return a score (0-1).

        Phase 6.0: NOT_IMPLEMENTED.
        """
        raise NotImplementedError(
            "Phase 6.0: DESIGN_ONLY. evaluate_candidate() will be implemented in Phase 6.1."
        )

    def plan(
        self,
        capability_ids: List[str],
        max_proposals: int = 5,
        **kwargs,
    ) -> PlannerOutput:
        """Generate all valid composition proposals for the given capabilities.

        Phase 6.0: NOT_IMPLEMENTED.
        """
        raise NotImplementedError(
            "Phase 6.0: DESIGN_ONLY. plan() will be implemented in Phase 6.1."
        )

    def validate_proposal(
        self, proposal: CompositeCapabilityProposal
    ) -> List[str]:
        """Validate a proposal against composition rules. Returns warnings.

        Phase 6.0: NOT_IMPLEMENTED.
        """
        raise NotImplementedError(
            "Phase 6.0: DESIGN_ONLY. validate_proposal() will be implemented in Phase 6.1."
        )

    def rank_proposals(
        self, proposals: List[CompositeCapabilityProposal]
    ) -> List[CompositeCapabilityProposal]:
        """Rank proposals by score, descending.

        Phase 6.0: NOT_IMPLEMENTED.
        """
        raise NotImplementedError(
            "Phase 6.0: DESIGN_ONLY. rank_proposals() will be implemented in Phase 6.1."
        )

    def __repr__(self) -> str:
        return "CompositionPlanner(status=DESIGN_ONLY)"