"""
Phase 4.3: Feedback Loop — ExperienceGraph, HealthReport, EvolutionProposal.

Architecture (corrected):
    ExecutionExperience (from Runtime)
            │
            ▼
    ExperienceGraph.write(exp)         ← write/persist/route ONLY
            │
            ├── Persist (JSONL)        ← filesystem write
            ├── Evidence.produce()     ← Experience → Evidence transformation
            │       │
            │       ▼
            │   EvidenceView           ← Registry reads from this
            │       │
            │       ▼
            │   Registry.consume_evidence()  ← reads EvidenceView, updates stats
            │
            └── Accumulator            ← in-memory for HealthReport
                    │
                    ▼
                HealthReport            ← descriptive ONLY
                    │
                    ▼
                EvolutionProposal       ← when signals warrant (draft status)

CRITICAL DESIGN:
    1. ExperienceGraph does NOT directly modify Capability/Implementation/Rule
    2. Evidence is produced FROM experience, Registry reads EvidenceView
    3. HealthReport is DESCRIPTIVE — not prescriptive
    4. EvolutionProposal requires Validation Gate for promotion beyond "proposed"
    5. EnhancementSignal says "I noticed" — not "do this"
    6. NO auto Capability change before Validation Gate
"""

from __future__ import annotations

import json
import os
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Optional

from dice.evidence import Evidence, EvidenceView, EvidenceStore, EvidenceType
from dice.runtime.experience.execution_models import ExecutionExperience

# Avoid circular imports — types are referenced by string where needed


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _uid(prefix: str = "") -> str:
    """Generate a short unique ID."""
    return f"{prefix}{uuid.uuid4().hex[:8]}"


# ═══════════════════════════════════════════════════════════════════════════
# EnhancementSignal
# ═══════════════════════════════════════════════════════════════════════════


@dataclass
class EnhancementSignal:
    """
    A signal that the system noticed something that COULD warrant attention.

    DESCRIPTIVE ONLY — says "I noticed X", NOT "you should do Y".

    Signals are data points generated from accumulated ExecutionExperiences.
    They are the raw material that EvolutionProposals are built from, but
    a signal alone does NOT trigger any change.

    Example:
        EnhancementSignal(
            signal_type="vocabulary_gap",
            severity="warning",
            description="Term 'cell lysis buffer' appeared in 3 failures but is not in capability vocabulary",
            evidence={"missing_terms": ["cell lysis buffer"], "failure_count": 3},
        )
        # NOT:
        # EnhancementSignal(
        #     signal_type="vocabulary_gap",
        #     severity="warning",
        #     description="Add 'cell lysis buffer' to capability vocabulary",
        #     evidence={"missing_terms": ["cell lysis buffer"]},
        # )
    """

    signal_type: str = ""         # "vocabulary_gap", "pattern_mismatch", "confidence_drop",
                                  # "high_failure_rate", "cross_domain_failure",
                                  # "implementation_underperformance", "insufficient_data",
                                  # "performance_degrading", "recurring_failure_pattern"
    severity: str = "info"        # "info", "warning", "critical"
    description: str = ""
    evidence: dict[str, Any] = field(default_factory=dict)
    generated_at: str = field(default_factory=_now)

    def to_dict(self) -> dict[str, Any]:
        return {
            "signal_type": self.signal_type,
            "severity": self.severity,
            "description": self.description,
            "evidence": self.evidence,
            "generated_at": self.generated_at,
        }


# ═══════════════════════════════════════════════════════════════════════════
# HealthReport
# ═══════════════════════════════════════════════════════════════════════════


@dataclass
class HealthReport:
    """
    Per-Capability health assessment derived from accumulated experiences.

    DESCRIPTIVE ONLY — describes what the data shows, does NOT prescribe
    what to do. Generated by ExperienceGraph.compute_health().

    Computed fields:
        trend: "improving" if recent success > historical, "degrading" if worse,
               "stable" otherwise.
        confidence_trend: same logic applied to confidence scores.
        top_failure_reasons: most common failure reasons from recent failures.
        signals: EnhancementSignals derived from the data.
    """

    capability_id: str = ""
    capability_name: str = ""

    # ── Execution statistics ──
    total_executions: int = 0
    success_count: int = 0
    failure_count: int = 0
    success_rate: float = 0.0

    # ── Trend analysis (recent window vs historical) ──
    recent_success_rate: float = 0.0       # last N executions
    recent_window_size: int = 20
    trend: str = "stable"                  # "improving", "stable", "degrading"

    # ── Failure analysis ──
    top_failure_reasons: list[dict[str, Any]] = field(default_factory=list)
    # [{"reason": "no_capability_match", "count": 5, "pct": 50.0}, ...]

    # ── Confidence analysis ──
    avg_confidence: float = 0.0
    confidence_trend: str = "stable"       # "improving", "stable", "degrading"

    # ── Signals (NOT prescriptions) ──
    signals: list[EnhancementSignal] = field(default_factory=list)

    # ── Metadata ──
    generated_at: str = field(default_factory=_now)
    data_window_start: str = ""
    data_window_end: str = ""
    experience_ids_analyzed: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "capability_id": self.capability_id,
            "capability_name": self.capability_name,
            "total_executions": self.total_executions,
            "success_count": self.success_count,
            "failure_count": self.failure_count,
            "success_rate": round(self.success_rate, 4),
            "recent_success_rate": round(self.recent_success_rate, 4),
            "recent_window_size": self.recent_window_size,
            "trend": self.trend,
            "top_failure_reasons": self.top_failure_reasons,
            "avg_confidence": round(self.avg_confidence, 4),
            "confidence_trend": self.confidence_trend,
            "signals": [s.to_dict() for s in self.signals],
            "generated_at": self.generated_at,
            "experience_ids_analyzed": len(self.experience_ids_analyzed),
        }

    def has_critical_signals(self) -> bool:
        """Check if there are any critical-severity signals."""
        return any(s.severity == "critical" for s in self.signals)

    def has_actionable_signals(self) -> bool:
        """Check if there are warning-or-above signals that warrant a proposal."""
        return any(s.severity in ("warning", "critical") for s in self.signals)


# ═══════════════════════════════════════════════════════════════════════════
# EvolutionProposal
# ═══════════════════════════════════════════════════════════════════════════


@dataclass
class EvolutionProposal:
    """
    A structured proposal for evolving a Capability.

    Generated when HealthReport detects actionable signals. Does NOT
    auto-apply — must go through Validation Gate.

    Status lifecycle:
        draft      — generated but not yet reviewed
        proposed   — submitted for validation
        validated  — passed through Validation Gate
        applied    — changes have been applied (external action)
        rejected   — did not pass Validation Gate or was declined

    The Feedback Loop CANNOT move status beyond "proposed". Only the
    Validation Gate can set "validated", "applied", or "rejected".
    """

    id: str = ""
    capability_id: str = ""
    capability_name: str = ""
    proposal_type: str = ""         # "vocabulary_gap_observed", "pattern_coverage_gap",
                                    # "confidence_instability", "scope_boundary_uncertain",
                                    # "performance_degradation", "recurring_failure_pattern",
                                    # "implementation_strategy_mismatch"

    # ── Source trace (MANDATORY) ──
    trigger_signals: list[EnhancementSignal] = field(default_factory=list)
    trigger_experience_ids: list[str] = field(default_factory=list)
    trigger_evidence_ids: list[str] = field(default_factory=list)    # 🆕 evidence trace
    health_at_generation: Optional[HealthReport] = None

    # ── What was observed (NOT what to do) ──
    observed_phenomenon: dict[str, Any] = field(default_factory=dict)
    # Structured description of WHAT was observed:
    #   vocabulary_gap_observed: {"domain": "components", "unmatched_terms_frequency": {...}}
    #   performance_degradation: {"recent_rate": 0.4, "historical_rate": 0.8, "delta": -0.4}
    #   pattern_coverage_gap: {"unmatched_structure_types": ["collapsed_table_variant_2"]}

    # ── Rationale (why this matters, not what to change) ──
    rationale: str = ""

    # ── Validation requirements ──
    validation_required: list[str] = field(default_factory=list)
    # e.g. ["regression_guard", "cross_document_check", "confidence_threshold"]
    validation_results: list[dict[str, Any]] = field(default_factory=list)
    # e.g. [{"gate": "regression_guard", "passed": True, "detail": "..."}]

    # ── Status ──
    status: str = "draft"           # "draft" → "proposed" → "validated" → "applied" | "rejected"

    # ── Metadata ──
    created_at: str = field(default_factory=_now)
    updated_at: str = field(default_factory=_now)
    created_by: str = "feedback_loop"
    notes: list[str] = field(default_factory=list)

    def __post_init__(self):
        if not self.id:
            self.id = _uid("EVO-PROP-")

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "capability_id": self.capability_id,
            "capability_name": self.capability_name,
            "proposal_type": self.proposal_type,
            "trigger_signal_types": [s.signal_type for s in self.trigger_signals],
            "trigger_experience_count": len(self.trigger_experience_ids),
            "trigger_evidence_count": len(self.trigger_evidence_ids),
            "observed_phenomenon": self.observed_phenomenon,
            "rationale": self.rationale[:500],
            "validation_required": self.validation_required,
            "validation_results": self.validation_results,
            "status": self.status,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "notes": self.notes,
        }

    def submit(self) -> None:
        """Submit for validation (status: draft → proposed)."""
        if self.status == "draft":
            self.status = "proposed"
            self.updated_at = _now()
            self.notes.append(f"[{_now()}] Submitted for validation")

    def validate(self, results: list[dict[str, Any]]) -> None:
        """
        Record validation results (called by Validation Gate only).
        Status: proposed → validated | rejected.
        """
        if self.status != "proposed":
            return
        self.validation_results = results
        all_passed = all(r.get("passed", False) for r in results)
        self.status = "validated" if all_passed else "rejected"
        self.updated_at = _now()
        self.notes.append(
            f"[{_now()}] Validation {'passed' if all_passed else 'failed'}: "
            f"{len([r for r in results if r.get('passed')])}/{len(results)} gates"
        )

    def mark_applied(self) -> None:
        """Mark as applied (external action completed)."""
        self.status = "applied"
        self.updated_at = _now()
        self.notes.append(f"[{_now()}] Changes applied")

    def mark_rejected(self, reason: str = "") -> None:
        """Reject the proposal."""
        self.status = "rejected"
        self.updated_at = _now()
        if reason:
            self.notes.append(f"[{_now()}] Rejected: {reason}")

    def can_be_promoted(self) -> bool:
        """Can this proposal move to 'proposed'?"""
        return self.status == "draft"

    def needs_validation(self) -> bool:
        """Does this proposal still need validation?"""
        return self.status in ("draft", "proposed")


# ═══════════════════════════════════════════════════════════════════════════
# ExperienceGraph (Write Interface)
# ═══════════════════════════════════════════════════════════════════════════


@dataclass
class GraphWriteResult:
    """Result of writing an experience to the ExperienceGraph."""
    experience_id: str = ""
    persisted: bool = False
    evidence_produced: int = 0           # 🆕 how many Evidence nodes were produced
    evidence_persisted: int = 0          # 🆕 how many Evidence nodes were persisted
    health_updated: bool = False
    proposals_generated: int = 0
    errors: list[str] = field(default_factory=list)
    timestamp: str = field(default_factory=_now)


class ExperienceGraph:
    """
    Write-side of the Feedback Loop.

    Accepts ExecutionExperience records and:
    1. Persists them to filesystem (JSON per-capability append log)
    2. Transforms experience → Evidence nodes (Evidence.produce)
    3. Persists Evidence to EvidenceStore
    4. Routes Evidence to EvidenceView (Registry reads from this)
    5. Accumulates in-memory data for HealthReport computation
    6. Generates EvolutionProposal when signals warrant

    KEY DESIGN (corrected):
    - This is a WRITE interface — it stores, routes, and accumulates.
    - Does NOT directly modify Capability definition, Implementation, or Rule code.
    - Does NOT directly call Registry methods (no registry.update_evidence()).
    - EvidenceView is the read interface that Registry consumes.
    - HealthReport is computed on demand from accumulated data.
    - EvolutionProposal is generated with status "draft" — never auto-applied.
    """

    def __init__(
        self,
        registry: Any = None,           # CapabilityRegistry (for cap name lookups only)
        storage_dir: str = "dice_output/experiences",
        evidence_store: Optional[EvidenceStore] = None,
    ):
        self._registry = registry
        self._storage_dir = storage_dir
        os.makedirs(self._storage_dir, exist_ok=True)

        # 🆕 Evidence layer
        self._evidence_store = evidence_store or EvidenceStore(
            storage_dir=os.path.join(os.path.dirname(storage_dir), "evidence")
        )
        self._evidence_view = EvidenceView()

        # In-memory accumulator: capability_id → list[ExecutionExperience]
        self._experiences: dict[str, list[ExecutionExperience]] = {}

        # Write log: list of GraphWriteResult
        self._write_log: list[GraphWriteResult] = []

        # Generated proposals
        self._proposals: dict[str, list[EvolutionProposal]] = {}

    # ═══════════════════════════════════════════════════════════════════
    # READ-ONLY ACCESSORS (for consumers)
    # ═══════════════════════════════════════════════════════════════════

    @property
    def evidence_view(self) -> EvidenceView:
        """
        The EvidenceView that Registry reads from.

        This is the BRIDGE between ExperienceGraph and Registry.
        Registry calls evidence_view.by_capability() to get evidence
        and update its internal stats.
        """
        return self._evidence_view

    # ═══════════════════════════════════════════════════════════════════
    # WRITE
    # ═══════════════════════════════════════════════════════════════════

    def write(self, experience: ExecutionExperience) -> GraphWriteResult:
        """
        Write a single ExecutionExperience to the graph.

        This is THE entry point for the Feedback Loop. Every execution
        (success or failure) MUST flow through this method.

        Steps:
            1. Persist experience to filesystem
            2. Produce Evidence nodes from experience
            3. Persist Evidence to EvidenceStore
            4. Route Evidence to EvidenceView (for Registry)
            5. Accumulate for health
            6. Check if signals warrant EvolutionProposal generation

        NOTE: Does NOT call Registry directly. EvidenceView is the interface.
        """
        result = GraphWriteResult(experience_id=experience.id)
        errors: list[str] = []

        # Step 1: Persist experience to filesystem
        try:
            self._persist_experience(experience)
            result.persisted = True
        except Exception as e:
            errors.append(f"Persist failed: {e}")

        # Step 2: Produce Evidence from experience
        evidence_nodes: list[Evidence] = []
        try:
            evidence_nodes = Evidence.from_experience(experience)
            result.evidence_produced = len(evidence_nodes)
        except Exception as e:
            errors.append(f"Evidence production failed: {e}")

        # Step 3: Persist Evidence
        try:
            result.evidence_persisted = self._evidence_store.persist(evidence_nodes)
        except Exception as e:
            errors.append(f"Evidence persist failed: {e}")

        # Step 4: Route Evidence to EvidenceView (Registry reads from this)
        self._evidence_view.add(evidence_nodes)

        # Step 5: Accumulate in memory
        self._accumulate(experience)
        result.health_updated = True

        # Step 6: Check for EvolutionProposal generation
        if experience.capability_id and experience.capability_id != "unknown":
            if experience.is_significant():
                proposals = self._maybe_generate_proposals(
                    experience.capability_id,
                    evidence_nodes=evidence_nodes,
                )
                result.proposals_generated = len(proposals)

        result.errors = errors
        self._write_log.append(result)
        return result

    # ═══════════════════════════════════════════════════════════════════
    # Persistence
    # ═══════════════════════════════════════════════════════════════════

    def _persist_experience(self, experience: ExecutionExperience) -> None:
        """Append an experience to the capability's JSON log file."""
        cid = experience.capability_id or "unknown"
        cap_dir = os.path.join(self._storage_dir, cid.replace("/", "_"))
        os.makedirs(cap_dir, exist_ok=True)

        filepath = os.path.join(cap_dir, "experiences.jsonl")
        with open(filepath, "a", encoding="utf-8") as f:
            f.write(json.dumps(experience.to_dict(), ensure_ascii=False) + "\n")

    # ═══════════════════════════════════════════════════════════════════
    # Accumulation
    # ═══════════════════════════════════════════════════════════════════

    def _accumulate(self, experience: ExecutionExperience) -> None:
        """Accumulate experience in memory for health computation."""
        cid = experience.capability_id
        if cid not in self._experiences:
            self._experiences[cid] = []
        self._experiences[cid].append(experience)

    # ═══════════════════════════════════════════════════════════════════
    # QUERY (read-side — lightweight)
    # ═══════════════════════════════════════════════════════════════════

    def get_capability_experiences(
        self, capability_id: str, limit: int = 50
    ) -> list[ExecutionExperience]:
        """Get recent experiences for a capability (most recent first)."""
        exps = self._experiences.get(capability_id, [])
        return sorted(exps, key=lambda e: e.timestamp, reverse=True)[:limit]

    def get_recent(self, limit: int = 50) -> list[ExecutionExperience]:
        """Get most recent experiences across all capabilities."""
        all_exps = []
        for exps in self._experiences.values():
            all_exps.extend(exps)
        return sorted(all_exps, key=lambda e: e.timestamp, reverse=True)[:limit]

    def get_experience_count(self, capability_id: str = "") -> int:
        """Count experiences for a capability (or total if no ID given)."""
        if capability_id:
            return len(self._experiences.get(capability_id, []))
        return sum(len(exps) for exps in self._experiences.values())

    # ═══════════════════════════════════════════════════════════════════
    # HEALTH REPORT
    # ═══════════════════════════════════════════════════════════════════

    def compute_health(
        self,
        capability_id: str,
        capability_name: str = "",
        recent_window: int = 20,
    ) -> HealthReport:
        """
        Compute a HealthReport from accumulated experiences.

        This is DERIVED DATA — computed on demand, not stored.
        Does NOT modify anything.

        Returns a HealthReport even if there are zero experiences
        (with success_rate=0.0 and no signals).
        """
        experiences = self._experiences.get(capability_id, [])

        report = HealthReport(
            capability_id=capability_id,
            capability_name=capability_name,
            recent_window_size=recent_window,
            data_window_start=experiences[0].timestamp if experiences else "",
            data_window_end=experiences[-1].timestamp if experiences else "",
            experience_ids_analyzed=[e.id for e in experiences],
        )

        if not experiences:
            return report

        # ── Basic statistics ──
        report.total_executions = len(experiences)
        report.success_count = sum(1 for e in experiences if e.success)
        report.failure_count = report.total_executions - report.success_count
        report.success_rate = (
            report.success_count / report.total_executions
            if report.total_executions > 0
            else 0.0
        )

        # ── Trend analysis ──
        recent = experiences[-recent_window:] if len(experiences) >= recent_window else experiences
        historical = experiences[:-recent_window] if len(experiences) > recent_window else []
        recent_success = sum(1 for e in recent if e.success)
        report.recent_success_rate = (
            recent_success / len(recent) if recent else 0.0
        )

        if historical:
            hist_success_rate = sum(1 for e in historical if e.success) / len(historical)
            delta = report.recent_success_rate - hist_success_rate
            if delta > 0.05:
                report.trend = "improving"
            elif delta < -0.05:
                report.trend = "degrading"
            else:
                report.trend = "stable"
        else:
            report.trend = "stable"

        # ── Failure analysis ──
        failures = [e for e in experiences if not e.success]
        if failures:
            reason_counts: dict[str, int] = {}
            for f in failures:
                reason = f.failure_reason or "unknown"
                reason_key = reason[:100]
                reason_counts[reason_key] = reason_counts.get(reason_key, 0) + 1

            sorted_reasons = sorted(
                reason_counts.items(), key=lambda x: x[1], reverse=True
            )
            total_failures = len(failures)
            report.top_failure_reasons = [
                {
                    "reason": reason,
                    "count": count,
                    "pct": round(count / total_failures * 100, 1),
                }
                for reason, count in sorted_reasons[:5]
            ]

        # ── Confidence analysis ──
        confidences = [e.confidence_after for e in experiences if e.confidence_after > 0]
        if confidences:
            report.avg_confidence = sum(confidences) / len(confidences)
            recent_confs = [
                e.confidence_after for e in recent if e.confidence_after > 0
            ]
            if recent_confs:
                recent_avg = sum(recent_confs) / len(recent_confs)
                if recent_avg > report.avg_confidence + 0.05:
                    report.confidence_trend = "improving"
                elif recent_avg < report.avg_confidence - 0.05:
                    report.confidence_trend = "degrading"
                else:
                    report.confidence_trend = "stable"

        # ── Generate signals ──
        report.signals = self._derive_signals(report, experiences)

        return report

    def _derive_signals(
        self,
        report: HealthReport,
        experiences: list[ExecutionExperience],
    ) -> list[EnhancementSignal]:
        """
        Derive EnhancementSignals from health data.

        DESCRIPTIVE ONLY — says what the data shows, NOT what to do.

        Signal thresholds (tunable observation rules, not prescriptions):
        - success_rate < 0.5 AND >= 5 executions → "high_failure_rate" (warning)
        - success_rate < 0.3 AND >= 5 executions → "high_failure_rate" (critical)
        - trend == "degrading" → "performance_degrading" (warning)
        - > 3 failures with same reason → "recurring_failure_pattern" (warning)
        - confidence_delta consistently negative → "confidence_drop" (info)
        - low execution count → "insufficient_data" (info)
        """
        signals: list[EnhancementSignal] = []

        # Signal: High failure rate
        if report.total_executions >= 5:
            if report.success_rate < 0.3:
                signals.append(EnhancementSignal(
                    signal_type="high_failure_rate",
                    severity="critical",
                    description=(
                        f"Success rate is {report.success_rate:.1%} "
                        f"({report.success_count}/{report.total_executions}) — critically low"
                    ),
                    evidence={
                        "success_rate": report.success_rate,
                        "total": report.total_executions,
                        "success_count": report.success_count,
                    },
                ))
            elif report.success_rate < 0.5:
                signals.append(EnhancementSignal(
                    signal_type="high_failure_rate",
                    severity="warning",
                    description=(
                        f"Success rate is {report.success_rate:.1%} "
                        f"({report.success_count}/{report.total_executions}) — below threshold"
                    ),
                    evidence={
                        "success_rate": report.success_rate,
                        "total": report.total_executions,
                        "success_count": report.success_count,
                    },
                ))

        # Signal: Degrading performance
        if report.trend == "degrading":
            signals.append(EnhancementSignal(
                signal_type="performance_degrading",
                severity="warning",
                description=(
                    f"Recent success rate ({report.recent_success_rate:.1%}) "
                    f"lower than historical ({report.success_rate:.1%})"
                ),
                evidence={
                    "recent_success_rate": report.recent_success_rate,
                    "overall_success_rate": report.success_rate,
                    "trend": report.trend,
                },
            ))

        # Signal: Recurring failure pattern
        for fr in report.top_failure_reasons:
            if fr.get("count", 0) >= 3:
                signals.append(EnhancementSignal(
                    signal_type="recurring_failure_pattern",
                    severity="warning",
                    description=(
                        f"Failure reason '{fr['reason'][:80]}' occurred "
                        f"{fr['count']} times ({fr['pct']}% of failures)"
                    ),
                    evidence={
                        "failure_reason": fr["reason"],
                        "count": fr["count"],
                        "pct": fr["pct"],
                    },
                ))

        # Signal: Confidence drop
        if report.confidence_trend == "degrading":
            signals.append(EnhancementSignal(
                signal_type="confidence_drop",
                severity="info",
                description="Average execution confidence is trending downward",
                evidence={
                    "avg_confidence": report.avg_confidence,
                    "confidence_trend": report.confidence_trend,
                },
            ))

        # Signal: Insufficient data
        if report.total_executions < 3 and report.total_executions > 0:
            signals.append(EnhancementSignal(
                signal_type="insufficient_data",
                severity="info",
                description=(
                    f"Only {report.total_executions} executions recorded — "
                    f"insufficient data for reliable health assessment"
                ),
                evidence={"total_executions": report.total_executions},
            ))

        return signals

    # ═══════════════════════════════════════════════════════════════════
    # EVOLUTION PROPOSAL
    # ═══════════════════════════════════════════════════════════════════

    def _maybe_generate_proposals(
        self,
        capability_id: str,
        evidence_nodes: Optional[list[Evidence]] = None,
    ) -> list[EvolutionProposal]:
        """
        Check if accumulated data warrants generating EvolutionProposals.

        Generates proposals only when HealthReport shows actionable signals.
        All proposals start with status "draft" — NEVER auto-applied.

        Evidence trace: includes both trigger_experience_ids and
        trigger_evidence_ids for full source traceability.
        """
        cap_name = ""
        if self._registry:
            cap = self._registry.get(capability_id)
            if cap:
                cap_name = cap.name

        health = self.compute_health(capability_id, capability_name=cap_name)

        if not health.has_actionable_signals():
            return []

        proposals: list[EvolutionProposal] = []

        # Track evidence IDs for traceability
        evd_ids = [e.id for e in (evidence_nodes or [])]

        # Proposal type 1: High failure rate observed
        for signal in health.signals:
            if signal.signal_type == "high_failure_rate" and signal.severity == "critical":
                proposal = EvolutionProposal(
                    capability_id=capability_id,
                    capability_name=cap_name,
                    proposal_type="performance_degradation",
                    trigger_signals=[signal],
                    trigger_experience_ids=health.experience_ids_analyzed,
                    trigger_evidence_ids=evd_ids,
                    health_at_generation=health,
                    observed_phenomenon={
                        "observation": "critically_low_success_rate",
                        "success_rate": health.success_rate,
                        "total_executions": health.total_executions,
                        "top_failure_reason": (
                            health.top_failure_reasons[0]
                            if health.top_failure_reasons else "unknown"
                        ),
                    },
                    rationale=(
                        f"Success rate is critically low at {health.success_rate:.1%} "
                        f"after {health.total_executions} executions. "
                        f"Top failure reason: "
                        f"{health.top_failure_reasons[0]['reason'][:100] if health.top_failure_reasons else 'unknown'}"
                    ),
                    validation_required=[
                        "regression_guard",
                        "cross_document_check",
                        "success_rate_threshold_50pct",
                    ],
                )
                proposals.append(proposal)

        # Proposal type 2: Performance degrading observed
        for signal in health.signals:
            if signal.signal_type == "performance_degrading":
                proposal = EvolutionProposal(
                    capability_id=capability_id,
                    capability_name=cap_name,
                    proposal_type="performance_degradation",
                    trigger_signals=[signal],
                    trigger_experience_ids=health.experience_ids_analyzed,
                    trigger_evidence_ids=evd_ids,
                    health_at_generation=health,
                    observed_phenomenon={
                        "observation": "performance_degrading",
                        "recent_success_rate": health.recent_success_rate,
                        "overall_success_rate": health.success_rate,
                        "delta": round(health.recent_success_rate - health.success_rate, 4),
                    },
                    rationale=(
                        f"Recent success rate ({health.recent_success_rate:.1%}) "
                        f"is lower than historical average ({health.success_rate:.1%}). "
                        f"This may indicate that new document types or content patterns "
                        f"are not well served by the current capability."
                    ),
                    validation_required=[
                        "degradation_root_cause_analysis",
                        "cross_document_check",
                    ],
                )
                proposals.append(proposal)

        # Proposal type 3: Recurring failure pattern observed
        for signal in health.signals:
            if signal.signal_type == "recurring_failure_pattern":
                proposal = EvolutionProposal(
                    capability_id=capability_id,
                    capability_name=cap_name,
                    proposal_type="recurring_failure_pattern",
                    trigger_signals=[signal],
                    trigger_experience_ids=health.experience_ids_analyzed,
                    trigger_evidence_ids=evd_ids,
                    health_at_generation=health,
                    observed_phenomenon={
                        "observation": "recurring_failure_pattern",
                        "failure_reason": signal.evidence.get("failure_reason", "unknown"),
                        "occurrence_count": signal.evidence.get("count", 0),
                        "pct_of_failures": signal.evidence.get("pct", 0),
                    },
                    rationale=(
                        f"A single failure reason accounts for "
                        f"{signal.evidence.get('pct', 0)}% of all failures "
                        f"({signal.evidence.get('count', 0)} occurrences). "
                        f"This suggests a systematic gap rather than random error."
                    ),
                    validation_required=[
                        "failure_pattern_consistency_check",
                        "cross_document_check",
                    ],
                )
                proposals.append(proposal)

        # Store proposals
        if capability_id not in self._proposals:
            self._proposals[capability_id] = []
        self._proposals[capability_id].extend(proposals)

        return proposals

    def generate_proposal(
        self, capability_id: str
    ) -> Optional[EvolutionProposal]:
        """
        Explicitly generate a proposal for a capability.
        Returns the most recent proposal, or None.
        """
        proposals = self._proposals.get(capability_id, [])
        if proposals:
            return proposals[-1]

        new_proposals = self._maybe_generate_proposals(capability_id)
        return new_proposals[-1] if new_proposals else None

    def get_proposals(
        self, capability_id: str = ""
    ) -> list[EvolutionProposal]:
        """Get all proposals (optionally filtered by capability)."""
        if capability_id:
            return self._proposals.get(capability_id, [])
        all_props = []
        for props in self._proposals.values():
            all_props.extend(props)
        return all_props

    def submit_proposal(self, proposal_id: str) -> bool:
        """Submit a draft proposal for validation."""
        for props in self._proposals.values():
            for p in props:
                if p.id == proposal_id:
                    if p.can_be_promoted():
                        p.submit()
                        return True
        return False

    # ═══════════════════════════════════════════════════════════════════
    # MAINTENANCE
    # ═══════════════════════════════════════════════════════════════════

    def clear(self, capability_id: str = "") -> None:
        """Clear accumulated experiences (for testing)."""
        if capability_id:
            self._experiences.pop(capability_id, None)
        else:
            self._experiences.clear()
        self._write_log.clear()
        self._proposals.clear()
        self._evidence_view.clear()

    def get_write_log(self) -> list[GraphWriteResult]:
        """Get the write log."""
        return list(self._write_log)


# ═══════════════════════════════════════════════════════════════════════════
# FeedbackLoop (Orchestrator)
# ═══════════════════════════════════════════════════════════════════════════


@dataclass
class FeedbackResult:
    """Result of processing one or more experiences through the FeedbackLoop."""
    experiences_processed: int = 0
    evidence_nodes_produced: int = 0        # 🆕
    errors: list[str] = field(default_factory=list)
    health_reports: dict[str, HealthReport] = field(default_factory=dict)
    proposals: list[EvolutionProposal] = field(default_factory=list)
    timestamp: str = field(default_factory=_now)


class FeedbackLoop:
    """
    Orchestrates the complete feedback pipeline.

    Wiring: ExecutionRuntime → FeedbackLoop → ExperienceGraph → EvidenceView → Registry

    The FeedbackLoop is the glue between the Runtime output (ExecutionExperience)
    and the Registry input (via EvidenceView). It does NOT contain
    business logic — it delegates to ExperienceGraph.

    The Registry reads from ExperienceGraph.evidence_view, not from the
    FeedbackLoop directly. This ensures the Evidence boundary.

    Usage:
        loop = FeedbackLoop(registry, storage_dir="dice_output/feedback")
        result = loop.process(experience)       # single
        result = loop.process_batch(experiences) # batch
        health = loop.get_health("CAP-COMP-TABLE")
        proposals = loop.get_proposals("CAP-COMP-TABLE")

        # Registry-side: consume evidence
        registry.consume_evidence(loop.graph.evidence_view)
    """

    def __init__(
        self,
        registry: Any = None,
        storage_dir: str = "dice_output/feedback",
    ):
        self._registry = registry
        self._graph = ExperienceGraph(
            registry=registry,
            storage_dir=storage_dir,
        )

    @property
    def graph(self) -> ExperienceGraph:
        """Access the underlying ExperienceGraph (including evidence_view)."""
        return self._graph

    @property
    def evidence_view(self) -> EvidenceView:
        """Access the EvidenceView (for Registry to consume)."""
        return self._graph.evidence_view

    def process(self, experience: ExecutionExperience) -> FeedbackResult:
        """
        Process a single ExecutionExperience through the feedback pipeline.

        Steps:
            1. Write to ExperienceGraph (persist + evidence + accumulate)
            2. Compute HealthReport
            3. Collect EvolutionProposals

        NOTE: Does NOT call Registry. Registry reads evidence_view separately.
        """
        result = FeedbackResult(experiences_processed=1)

        # Step 1: Write to graph (includes evidence production)
        write_result = self._graph.write(experience)
        result.evidence_nodes_produced = write_result.evidence_produced
        if write_result.errors:
            result.errors.extend(write_result.errors)

        # Step 2: Compute health (only if capability is known)
        if experience.capability_id and experience.capability_id != "unknown":
            health = self._graph.compute_health(experience.capability_id)
            result.health_reports[experience.capability_id] = health

        # Step 3: Collect proposals
        result.proposals = self._graph.get_proposals(experience.capability_id)

        return result

    def process_batch(
        self, experiences: list[ExecutionExperience]
    ) -> FeedbackResult:
        """Process multiple experiences in batch."""
        result = FeedbackResult(experiences_processed=len(experiences))

        affected_capabilities: set[str] = set()
        for exp in experiences:
            write_result = self._graph.write(exp)
            result.evidence_nodes_produced += write_result.evidence_produced
            if write_result.errors:
                result.errors.extend(write_result.errors)
            if exp.capability_id and exp.capability_id != "unknown":
                affected_capabilities.add(exp.capability_id)

        # Compute health for each affected capability
        for cid in affected_capabilities:
            health = self._graph.compute_health(cid)
            result.health_reports[cid] = health

        # Collect all proposals
        result.proposals = self._graph.get_proposals()

        return result

    def get_health(self, capability_id: str) -> HealthReport:
        """Get the latest health report for a capability."""
        return self._graph.compute_health(capability_id)

    def get_proposals(
        self, capability_id: str = ""
    ) -> list[EvolutionProposal]:
        """Get evolution proposals (optionally filtered)."""
        return self._graph.get_proposals(capability_id)

    def submit_proposal(self, proposal_id: str) -> bool:
        """Submit a proposal for validation."""
        return self._graph.submit_proposal(proposal_id)

    def clear(self) -> None:
        """Reset all accumulated state (for testing)."""
        self._graph.clear()
